package Client.Controller;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class DecreaseForm extends JDialog {
    private JPanel contentPane;
    private JButton OKButton;
    private JButton cancelButton;
    protected JTextField item;
    protected JComboBox searchType;
    protected JTextField Quantity;

    public DecreaseForm() {
        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(OKButton);

        OKButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onOK();
            }
        });

        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onCancel();
            }
        });

        // call onCancel() when cross is clicked
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                onCancel();
            }
        });

        // call onCancel() on ESCAPE
        contentPane.registerKeyboardAction(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                onCancel();
            }
        }, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
    }

    private void onOK() {
        // add your code here
        dispose();
    }

    private void onCancel() {
        
        dispose();
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        contentPane.setPreferredSize(new Dimension(350, 90));
        final JToolBar toolBar1 = new JToolBar();
        toolBar1.setBackground(new Color(-4662027));
        toolBar1.setFloatable(false);
        contentPane.add(toolBar1, BorderLayout.SOUTH);
        OKButton = new JButton();
        OKButton.setBackground(new Color(-11157259));
        OKButton.setForeground(new Color(-12828863));
        OKButton.setText("OK");
        toolBar1.add(OKButton);
        cancelButton = new JButton();
        cancelButton.setBackground(new Color(-11157259));
        cancelButton.setForeground(new Color(-12828863));
        cancelButton.setText("Cancel");
        toolBar1.add(cancelButton);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        contentPane.add(panel1, BorderLayout.CENTER);
        item = new JTextField();
        item.setBackground(new Color(-2180105));
        item.setCaretColor(new Color(-12828863));
        item.setForeground(new Color(-12828863));
        item.setMinimumSize(new Dimension(100, 30));
        item.setPreferredSize(new Dimension(100, 30));
        panel1.add(item, BorderLayout.CENTER);
        searchType = new JComboBox();
        searchType.setBackground(new Color(-3562530));
        searchType.setMinimumSize(new Dimension(90, 30));
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Item ID");
        defaultComboBoxModel1.addElement("Item Name");
        searchType.setModel(defaultComboBoxModel1);
        searchType.setPreferredSize(new Dimension(90, 30));
        panel1.add(searchType, BorderLayout.WEST);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel1.add(panel2, BorderLayout.NORTH);
        Quantity = new JTextField();
        Quantity.setBackground(new Color(-2180105));
        Quantity.setForeground(new Color(-12828863));
        Quantity.setMinimumSize(new Dimension(100, 30));
        Quantity.setPreferredSize(new Dimension(100, 30));
        Quantity.setText("");
        panel2.add(Quantity, BorderLayout.CENTER);
        final JLabel label1 = new JLabel();
        label1.setBackground(new Color(-4662027));
        label1.setForeground(new Color(-12828863));
        label1.setText("Enter amount to decrease quantity by:");
        panel2.add(label1, BorderLayout.WEST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
