package Client.View;

import Client.Controller.Listener;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * This implements the GUI
 *
 * @author Christina Lu 30037885, Layla Arab 30017060, MD Rashik Hassan 30048022
 * @version 1.0
 * @since April 5 2019
 */
public class UserGUI {
    /**
     * panel containing other items of gui
     */
    private JPanel panel;
    /**
     * button to show all tools
     */
    private JButton showToolsButton;
    /**
     * area to show the list of items
     */
    private JTextArea ItemList;
    /**
     * field to input text
     */
    private JTextField textField1;
    /**
     * button to search for an item
     */
    private JButton searchButton;
    private JButton decreaseQuantityButton;
    private JButton checkQuantityButton;
    //    private JTable ItemTable;

    /**
     * listener object to react to action in gui
     */

    private Listener listener;
    //private JTable ItemTable;

    /**
     * Default constructor for the GUI
     */
    public UserGUI() {
    }

    /**
     * sets the listener
     *
     * @param listener listener
     */
    public void setListener(Listener listener) {
        this.listener = listener;
    }

    /**
     * Displays the tools of the "Show Tools" button is pressed
     */
    private void displayTools() {
        showToolsButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                String tools = listener.actionPerformed("DISPLAY");
//                String [] colHeaders = {"ID", "Item", "Quantity"};
                ItemList.setText(tools);
            }
        });

    }

    /**
     * searches for the tool if "search" button is pressed
     */
    private void searchTools() {
        showToolsButton.addActionListener(new ActionListener() {
            /**
             * Invoked when an action occurs.
             *
             * @param e the event to be processed
             */
            @Override
            public void actionPerformed(ActionEvent e) {

            }

        });
    }

    /**
     * updates the GUI
     *
     * @param gui the gui to be updated
     */
    public void updateView(UserGUI gui) {
        JFrame frame = new JFrame("Toolshop");
        frame.setContentPane(gui.panel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        gui.displayTools();
        gui.searchTools();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        panel.setMinimumSize(new Dimension(500, 500));
        panel.setPreferredSize(new Dimension(500, 500));
        final JToolBar toolBar1 = new JToolBar();
        toolBar1.setBackground(new Color(-1655851));
        toolBar1.setForeground(new Color(-1655851));
        panel.add(toolBar1, BorderLayout.NORTH);
        showToolsButton = new JButton();
        showToolsButton.setBackground(new Color(-1140324));
        showToolsButton.setForeground(new Color(-12828863));
        showToolsButton.setText("Show Tools");
        toolBar1.add(showToolsButton);
        textField1 = new JTextField();
        textField1.setBackground(new Color(-4662027));
        toolBar1.add(textField1);
        searchButton = new JButton();
        searchButton.setBackground(new Color(-1140324));
        searchButton.setForeground(new Color(-12828863));
        searchButton.setText("Search");
        toolBar1.add(searchButton);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setForeground(new Color(-4662027));
        panel.add(scrollPane1, BorderLayout.CENTER);
        ItemList = new JTextArea();
        ItemList.setBackground(new Color(-1657945));
        ItemList.setEditable(false);
        ItemList.setForeground(new Color(-12828863));
        scrollPane1.setViewportView(ItemList);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
